name: ollama_py
channels:
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - ollama==0.4.8
      - pandas==2.2.3
      - numpy==2.2.5
      - openpyxl==3.1.5
      - tqdm==4.67.1
      - pydantic==2.11.3
      - httpx==0.28.1
      - scikit-learn==1.7.0
      - scipy==1.16.0
